### [numpy](https://numpy.org/doc/stable/index.html)
#### edited version from [@KeithGalli](https://github.com/KeithGalli/NumPy)

In [81]:
import numpy as np

### The Basics

In [82]:
a = np.array([1,127,3], dtype='int8') # 8-bit integer (2's complement)
print(a)

[  1 127   3]


In [65]:
# 2d array
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [66]:
# Get Dimension
a.ndim

1

In [67]:
# Get Shape
b.shape # ex. (2,3) is 2 rows and 3 columns

(2, 3)

In [68]:
# Get Shape
a.shape # ex. (2,3) is 2 vectors with 3 elements each

(3,)

In [69]:
# Get Type
a.dtype

dtype('int8')

In [70]:
# Get Size
a.itemsize  #length of each element in bytes

1

In [71]:
# Get total size (in bytes)
a.nbytes

3

In [72]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [73]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [74]:
# Get a specific element [r, c]
print("v1 :",a[1, -2])
print("v2: ",a[1][-2]) #normal python list

v1 : 13
v2:  13


In [75]:
# Get a specific row 
a[0, ::2]

array([1, 3, 5, 7])

In [76]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [77]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1::2] # or a[0,1:-1:2]

array([2, 4, 6])

In [78]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [79]:
b = np.array([[[1,2,1],[3,4,2]],[[5,6,3],[7,8,4]]])
print(b)
b.shape

[[[1 2 1]
  [3 4 2]]

 [[5 6 3]
  [7 8 4]]]


(2, 2, 3)

In [80]:
# Get specific element (work outside in)
b[0,1,1]

4

In [95]:
print(b[0,1,:-1:])

[3 4]


In [101]:
# replace 
b[0,1,:-1:] = [0,0]
b

array([[[1, 2, 1],
        [0, 0, 2]],

       [[5, 6, 3],
        [7, 8, 4]]])

### Initializing Different Types of Arrays

In [99]:
# All 0s matrix
np.zeros((2,3)) # use shape as a tuple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [103]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [104]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [106]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [110]:
# Any other number (full_like)
np.full_like(a, 99)

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [56]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.07805642, 0.53385716],
       [0.02494273, 0.99955252],
       [0.48588042, 0.91247437],
       [0.27779213, 0.16597751]])

In [73]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-2, -4, -4],
       [ 6,  6,  3],
       [ 3,  2,  2]])

In [76]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [192]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [206]:
arr2 = np.array([[1, 2],
                [3, 4]])
r2 = np.repeat(arr2, 2, axis=0)
print("axis=0:\n",r2)
r2 = np.repeat(arr2, 2, axis=1)
print("axis=1:\n",r2)

axis=0:
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]
axis=1:
 [[1 1 2 2]
 [3 3 4 4]]


##### Axis Concept in Numpy

The concept of axis in numpy is the direction along the rows or columns. For example, in a 2D array:

- `axis 0` is the direction along the rows.
- `axis 1` is the direction along the columns.

Consider a defined 2D array. 

###### Axis 0

> If we set `axis=0`, we are considering the row direction. Imagine rotating it in a circle. If we set `repeat=2`, we would end up with two instances of `[1 2]`

###### Axis 1

> On the other hand, if `axis=1`, it means we are considering the column direction. In this case, rotating would give us two 1's and two 2's, resulting in `[1 1 2 2]`.


In [126]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [135]:
print("deep copy")
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print("a:",a)
print("b:",b)

#but
print("shallow copy")
a = np.array([1,2,3])
b = a
b[0] = 100

print("a:",a)
print("b:",b)

deep copy
a: [1 2 3]
b: [100   2   3]
shallow copy
a: [100   2   3]
b: [100   2   3]


### Mathematics

In [148]:
a = np.array([1,2,3,4],dtype='int32')
print(a)

[1 2 3 4]


In [137]:
a + 2

array([3, 4, 5, 6])

In [138]:
a - 2

array([-1,  0,  1,  2])

In [139]:
a * 2

array([2, 4, 6, 8])

In [149]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [150]:
# a= np.array([1,2,3,4])
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [113]:
a ** 2 # a^2

array([ 1,  4,  9, 16], dtype=int32)

In [165]:
import math
a = np.array([math.pi/4])
# Take the trigonometric
print(f"sqrt(2)/2 = {math.sqrt(2)/2:.8f}")
np.set_printoptions(precision=8) #control the number of decimal places
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

sqrt(2)/2 = 0.70710678
[0.70710678]
[0.70710678]
[1.]


In [117]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [166]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [167]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [133]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [197]:
stats = np.random.randint(0, 100, size=(2,3))
print(stats)

[[ 8 11 50]
 [40 33 37]]


In [198]:
np.min(stats)

8

In [205]:
np.max(stats, axis=0)

array([40, 33, 50])

In [210]:
np.sum(stats, axis=0)

array([48, 44, 87])

### Reorganizing Arrays

In [231]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print("before:\n",before)

after = before.reshape((2,2,2))
print("after:\n",after)

# the condition is that the number of elements must be the same
# thus 2*4 = 2*2*2 

before:
 [[1 2 3 4]
 [5 6 7 8]]
after:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [222]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [232]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [234]:
filedata = np.genfromtxt('testNumpy.txt', delimiter=',')
filedata = filedata.astype('int64')
print(filedata)

[[  2  33  44  55 666  22   3   2   1   1   2   3   4   5   6   7   8   9]
 [  3  44  55  66 777  33   4   3   2   2   3   4   5   6   7   8   9   0]
 [  4  55  66  77 888  44   5   4   3   3   4   5   6   7   8   9   0   1]]


##### Boolean Masking and Advanced Indexing

In [240]:
(~((filedata > 2) & (filedata < 50)))

array([[ True, False, False,  True,  True, False, False,  True,  True,
         True,  True, False, False, False, False, False, False, False],
       [False, False,  True,  True,  True, False, False, False,  True,
         True, False, False, False, False, False, False, False,  True],
       [False,  True,  True,  True,  True, False, False, False, False,
        False, False, False, False, False, False, False,  True,  True]])